bam.update_building("silo-ore1", {{"steel-plate", 100}, {"stone-brick", 100}})
bam.update_building("silo-ore2", {{"steel-plate", 100}, {"stone-brick", 100}})
bam.update_building("silo-ore3", {{"steel-plate", 100}, {"stone-brick", 100}})
bam.update_building("silo-ore4", {{"steel-plate", 100}, {"stone-brick", 100}})
bam.update_building("silo-ore5", {{"steel-plate", 100}, {"stone-brick", 100}})
bam.update_building("silo-ore6", {{"steel-plate", 100}, {"stone-brick", 100}})
bam.update_building("silo-coal", {{"steel-plate", 100}, {"stone-brick", 100}})
