bam.update_building("angels-warehouse", {{"steel-plate", 100}, {"iron-plate", 200}, {"stone-brick", 200}})
bam.update_building("angels-warehouse-passive-provider", {{"steel-plate", 50}, {"angels-warehouse", 2}, {"advanced-circuit", 50}})
bam.update_building("angels-warehouse-active-provider", {{"steel-plate", 50}, {"angels-warehouse", 2}, {"advanced-circuit", 50}})
bam.update_building("angels-warehouse-storage", {{"steel-plate", 50}, {"angels-warehouse", 2}, {"advanced-circuit", 50}})
bam.update_building("angels-warehouse-requester", {{"steel-plate", 50}, {"angels-warehouse", 2}, {"advanced-circuit", 50}})
