bam.update_building("angels-warehouse", {{"steel-plate", 150}, {"iron-plate", 250}, {"stone-brick", 250}})
bam.update_building("angels-warehouse-passive-provider", {{"steel-plate", 100}, {"angels-warehouse", 20}, {"advanced-circuit", 100}})
bam.update_building("angels-warehouse-active-provider", {{"steel-plate", 100}, {"angels-warehouse", 20}, {"advanced-circuit", 100}})
bam.update_building("angels-warehouse-storage", {{"steel-plate", 100}, {"angels-warehouse", 20}, {"advanced-circuit", 100}})
bam.update_building("angels-warehouse-requester", {{"steel-plate", 100}, {"angels-warehouse", 20}, {"advanced-circuit", 100}})
