-- table.remove(data.raw["recipe"]["molten-aluminium-smelting"].ingredients,[1]={"ingot-aluminium", 1}
table.remove(data.raw["recipe"]["molten-aluminium-smelting"].ingredients,2)
table.remove(data.raw["recipe"]["liquid-titanium-tetrachloride-smelting"].ingredients,2)

table.insert(data.raw["technology"]["angels-copper-smelting"].effects,{type = "unlock-recipe", recipe = "angels-copper-plate"})
table.insert(data.raw["technology"]["angels-iron-smelting"].effects,{type = "unlock-recipe", recipe = "angels-iron-plate"})
table.insert(data.raw["technology"]["angels-lead-smelting"].effects,{type = "unlock-recipe", recipe = "angels-bob-lead-plate"})
table.insert(data.raw["technology"]["angels-tin-smelting"].effects,{type = "unlock-recipe", recipe = "angels-bob-tin-plate"})
table.insert(data.raw["technology"]["angels-aluminium-smelting"].effects,{type = "unlock-recipe", recipe = "angels-bob-aluminium-plate"})
table.insert(data.raw["technology"]["angels-silicon-smelting"].effects,{type = "unlock-recipe", recipe = "angels-bob-silicon-plate"})
table.insert(data.raw["technology"]["angels-silver-smelting"].effects,{type = "unlock-recipe", recipe = "angels-bob-silver-plate"})
table.insert(data.raw["technology"]["angels-zinc-smelting"].effects,{type = "unlock-recipe", recipe = "angels-bob-zinc-plate"})
table.insert(data.raw["technology"]["angels-cobalt-smelting"].effects,{type = "unlock-recipe", recipe = "angels-bob-cobalt-plate"})
table.insert(data.raw["technology"]["angels-nickel-smelting"].effects,{type = "unlock-recipe", recipe = "angels-bob-nickel-plate"})
table.insert(data.raw["technology"]["angels-gold-smelting"].effects,{type = "unlock-recipe", recipe = "angels-bob-gold-plate"})
table.insert(data.raw["technology"]["angels-titanium-smelting"].effects,{type = "unlock-recipe", recipe = "angels-bob-titanium-plate"})
table.insert(data.raw["technology"]["angels-tungsten-smelting"].effects,{type = "unlock-recipe", recipe = "angels-bob-tungsten-plate"})
table.insert(data.raw["technology"]["advanced-metallurgy-1"].effects,{type = "unlock-recipe", recipe = "ingot-iron-smelting"})
table.insert(data.raw["technology"]["advanced-metallurgy-1"].effects,{type = "unlock-recipe", recipe = "molten-steel-smelting"})
table.insert(data.raw["technology"]["advanced-metallurgy-1"].effects,{type = "unlock-recipe", recipe = "angels-steel-plate"})